[project]
name = "uv-project"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.14"
dependencies = [
    "jupyterlab>=4.5.0",
    "numpy>=2.3.5",
    "pandas>=2.3.3",
]
